name: HDPS
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pandas
  - python
  - numpy
  - matplotlib
  - natsort
  - seaborn
  - scipy
  - autograd
  - ipykernel
  - requests
  - jupyter
